name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    environment: Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Environment
        run: echo "Hello, world"
